server.port=@server.port@
spring.application.name=@project.name@
info.version=@project.version@
info.stage=dev
management.metrics.export.statsd.flavor=etsy
# --
spring:
    servlet.multipart:
        max-file-size: 10MB
        max-request-size: 10MB
        enabled: true
# --
storage:
    endpoint: localhost
    signingRegion: RU
    clientProtocol: HTTP
    clientMaxErrorRetry: 10
    bucketName: files
# ----
# for up local test version
#storage.endpoint=localhost:32827
#storage.signingRegion=RU
#storage.accessKey=test
#storage.secretKey=test
#storage.clientProtocol=HTTP
#storage.clientMaxErrorRetry=10
#storage.bucketName=TEST
