info:
  version: @project.version@
  stage: dev

server:
  port: @server.port@

management:
  security:
    flag: false
  server:
    port: @management.port@
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always

s3:
  endpoint: 'http://127.0.0.1:32827'
  bucket-name: 'files'
  signing-region: 'RU'
  client-protocol: 'http'
  client-max-error-retry: 10
  signer-override: 'S3SignerType'
#  signer-override: 'AWSS3V4SignerType'
  access-key: 'test'
  secret-key: 'test'

s3-sdk-v2:
  enabled: false
  endpoint: 'http://127.0.0.1:9000'
  bucket-name: 'files-v2'
  region: 'RU'
  access-key: 'test'
  secret-key: 'test'

testcontainers:
  ceph:
    tag: 'v3.0.5-stable-3.0-luminous-centos-7'
    accessKey: 'test'
    secretKey: 'test'
  minio:
    tag: 'latest'
    user: 'user'
    password: 'password'
